services:
  flask_app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app.py:/code/app.py
      - ./minesweep:/code/minesweep
      - ./templates:/code/templates
      - ./static:/code/static
      - ./data:/data
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
