version: '3'
services:
  flask_app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app.py:/code/app.py
      - ./minesweep:/code/minesweep
      - ./templates:/code/templates
      - ./static:/code/static
      - ./data:/data
      - ./data/online:/data/online
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

