version: '3'
services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./data:/data
      - ./data/online:/data/online
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=production

