# syntax=docker/dockerfile:1
FROM python:3.13-alpine
WORKDIR /code
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements_dev.txt requirements.txt
RUN pip install -r requirements.txt
RUN mkdir -p /data/online
ENV ENV=DEV

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
